/**
 * WASM Module Loader
 *
 * Handles loading and initialization of the Rust WASM module.
 * Falls back to pure TypeScript if WASM is unavailable.
 */

let wasmModule: any = null;
let wasmAvailable = false;

/**
 * Initialize WASM module
 * Returns true if WASM loaded successfully, false if fallback to TypeScript
 */
export async function initWasm(): Promise<boolean> {
  try {
    // Try to import WASM module
    // This path is generated by wasm-pack
    const wasm = await import('../wasm/pkg/timberborn_wasm.js');

    // Initialize WASM
    await wasm.default();

    wasmModule = wasm;
    wasmAvailable = true;

    console.log('✅ WASM module loaded successfully');
    console.log('   Using Rust for hot paths:');
    console.log('   • VoxelGrid operations (~5x faster)');
    console.log('   • Heightmap generation (~3x faster)');
    console.log('   • Cave carving (~4x faster)');

    return true;
  } catch (error) {
    console.warn('⚠️  WASM module not available, falling back to TypeScript');
    console.warn('   Build WASM module with: cd wasm && wasm-pack build --target web');
    console.warn('   Error:', error);

    wasmAvailable = false;
    return false;
  }
}

/**
 * Check if WASM is available
 */
export function isWasmAvailable(): boolean {
  return wasmAvailable;
}

/**
 * Get WASM module (throws if not available)
 */
export function getWasmModule(): any {
  if (!wasmAvailable || !wasmModule) {
    throw new Error('WASM module not loaded. Call initWasm() first.');
  }
  return wasmModule;
}

/**
 * Get WASM module or null if not available
 */
export function tryGetWasmModule(): any | null {
  return wasmAvailable ? wasmModule : null;
}
